# .github/workflows/update-activity.yml:

name: Update GitHub Activity

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update GitHub Activity
        uses: Axello0/activity-log_PLN1
        with:
          GITHUB_USERNAME: "Axello0"
          GITHUB_TOKEN: ${{ secrets.ACTIONSSECRETRDDT2024 }} # Ensure this matches the secret name in repository settings
